web:
  build: .
  ports:
    - "7000:80"
  volumes:
    - "$PWD/src:/var/www/html/"
  links:
    - db
db:
  image: mysql
  environment:
    - MYSQL_USER=user
    - MYSQL_PASSWORD=pass
    - MYSQL_ROOT_PASSWORD=pass
    - MYSQL_DATABASE=testdb
