web:
  image: pdxjohnny/points
  ports:
    - "6534:80"
  links:
    - db
db:
  image: mysql
  environment:
    - MYSQL_USER=user
    - MYSQL_PASSWORD=pass
    - MYSQL_ROOT_PASSWORD=pass
    - MYSQL_DATABASE=testdb
